/**
 * Communities where people ask for a tool or describe a job. Jev picks one
 * against the product. The key is the subreddit name.
 */
export const SUBREDDIT_CHOICES: Record<string, string> = {
  SaaS: "Founders and buyers of subscription software.",
  startups: "Early companies looking for tools and customers.",
  Entrepreneur: "People starting a business and shopping for help.",
  smallbusiness: "Owners of small companies describing daily problems.",
  sweatystartup: "Local service businesses and the tools they use.",
  SideProject: "Makers shipping small products and asking what to use.",
  marketing: "Marketers looking for channels, tools, and tactics.",
  digital_marketing: "People running online campaigns and comparing software.",
  PPC: "Advertisers buying clicks and managing ad accounts.",
  SEO: "People trying to rank pages and choosing SEO tools.",
  socialmedia: "People posting for brands and looking for schedulers.",
  copywriting: "Writers producing sales copy and looking for help.",
  sales: "Salespeople managing pipeline, outreach, and CRM.",
  ecommerce: "Online stores choosing carts, ads, and operations tools.",
  shopify: "Shopify store owners asking how to run the shop.",
  Etsy: "Sellers on Etsy asking about listings, fees, and tools.",
  freelance: "Freelancers looking for clients and the tools to run the work.",
  webdev: "Developers building sites and choosing libraries and hosts.",
  sysadmin: "IT people running company systems and looking for software.",
  devops: "Teams shipping infrastructure and choosing platforms.",
  selfhosted: "People hosting their own software instead of buying SaaS.",
  cybersecurity: "Security teams and practitioners choosing defenses.",
  accounting: "Bookkeepers and accountants closing the books.",
  bookkeeping: "People recording transactions for small companies.",
  realestate: "Agents and investors discussing deals and software.",
  landlords: "Property owners managing tenants, rent, and repairs.",
  Construction: "Builders and contractors running jobs and crews.",
  electricians: "Electricians talking about jobs, tools, and the trade.",
  plumbing: "Plumbers talking about jobs, tools, and customers.",
  mechanics: "Auto repair shops and technicians.",
  truckers: "Drivers and small fleets talking about the work.",
  logistics: "People moving goods and running warehouses.",
  manufacturing: "Factories and makers of physical products.",
  farming: "Farmers talking about crops, equipment, and the business.",
  photography: "Photographers finding clients and choosing gear and software.",
  filmmakers: "People making video and looking for tools and work.",
  podcasting: "People recording shows and choosing hosting and gear.",
  NewTubers: "New YouTube channels asking how to grow and what to use.",
  gamedev: "People making games and choosing engines and tools.",
  writers: "Writers working on books, articles, and client work.",
  teachers: "Teachers looking for classroom tools and materials.",
  edtech: "People building or buying education software.",
  parenting: "Parents describing family problems and what they use.",
  fitness: "People training and looking for programs, apps, and gear.",
  medicine: "Clinicians discussing care, tools, and practice.",
  nursing: "Nurses talking about the job and the tools on the floor.",
  dentistry: "Dentists and dental teams running a practice.",
  restaurants: "Owners and staff running restaurants.",
  KitchenConfidential: "Cooks and restaurant workers talking about the job.",
  AirBnB: "Hosts managing short-term rentals.",
  personalfinance: "People managing their own money and looking for help.",
  humanresources: "HR teams hiring, paying, and managing people.",
  recruiting: "Recruiters sourcing candidates and choosing tools.",
  userexperience: "Designers researching users and critiquing products.",
  productmanagement: "Product managers deciding what to build.",
  nocode: "People building software without writing code.",
  artificial: "People using and building AI products.",
  datascience: "People analyzing data and choosing tools.",
  productivity: "People organizing work and trying apps.",
};
